local config = require("mdemg.config")

describe("mdemg.config", function()
	before_each(function()
		config._config = nil
	end)

	describe("defaults", function()
		it("has expected default endpoint", function()
			assert.equals("http://localhost:9999", config.defaults.endpoint)
		end)

		it("has default timeout", function()
			assert.equals(30, config.defaults.timeout)
		end)

		it("has default keymaps", function()
			assert.is_not_nil(config.defaults.keymaps)
			assert.equals("<leader>mr", config.defaults.keymaps.recall)
			assert.equals("<leader>ms", config.defaults.keymaps.store)
		end)

		it("has default auto settings", function()
			assert.is_true(config.defaults.auto.ingest_on_save)
			assert.equals(2000, config.defaults.auto.ingest_debounce_ms)
			assert.equals(30, config.defaults.auto.health_poll_interval)
		end)

		it("has default UI settings", function()
			assert.equals("rounded", config.defaults.ui.border)
			assert.is_true(config.defaults.ui.use_telescope)
		end)
	end)

	describe("setup", function()
		it("merges user config with defaults", function()
			config.setup({ endpoint = "http://localhost:8888" })
			local cfg = config.get()
			assert.equals("http://localhost:8888", cfg.endpoint)
			assert.equals(30, cfg.timeout)
		end)

		it("deep merges nested config", function()
			config.setup({ keymaps = { recall = "<leader>xr" } })
			local cfg = config.get()
			assert.equals("<leader>xr", cfg.keymaps.recall)
			assert.equals("<leader>ms", cfg.keymaps.store)
		end)

		it("overrides auto settings", function()
			config.setup({ auto = { ingest_on_save = false } })
			local cfg = config.get()
			assert.is_false(cfg.auto.ingest_on_save)
			assert.equals(2000, cfg.auto.ingest_debounce_ms)
		end)
	end)

	describe("get", function()
		it("returns defaults when setup not called", function()
			local cfg = config.get()
			assert.equals(config.defaults.endpoint, cfg.endpoint)
		end)

		it("returns merged config after setup", function()
			config.setup({ space_id = "my-space" })
			local cfg = config.get()
			assert.equals("my-space", cfg.space_id)
		end)
	end)
end)
